#!/usr/bin/env python3
"""Generate LaTeX table for Overleaf: systematic old-vs-new filter comparison.
Uses NSP p_plus=True data (31 combos x 6 ptb, 5 seeds).

Narrative: sim_pt is the weakest/least-stable defense tip.
We propose nsp_pt and fc_pt as replacements. Controlled experiments
show replacing sim with nsp/fc systematically improves accuracy."""

import json, numpy as np

with open('advanced_report/5filter_combo_data.json') as f:
    data = json.load(f)

nsp = data['nsp_pp_true']  # NSP true-label, p_plus=True

PTBS = [0.0, 0.05, 0.1, 0.15, 0.2, 0.25]

def get_ptb(rd, ptb):
    """Get result for a ptb level, handling both float and string keys."""
    for k in [ptb, str(ptb), f'{ptb:.2f}', f'{ptb:.1f}']:
        if k in rd:
            return rd[k]
    return {}

def fmt(r, mark_unstable=True):
    """Format mean±std for LaTeX."""
    m = r.get('mean')
    s = r.get('std', 0)
    n = r.get('n', 0)
    if m is None or n == 0:
        return '\\text{NaN}'
    cell = f'{m:.4f}'
    if s >= 0.005 and n > 1:
        cell += f'$\\;\\pm\\;${s:.4f}'
    if n < 5 and mark_unstable:
        cell += '$^{{\\dagger}}$'
    return cell

def color_diff(val_old, val_new):
    """Return LaTeX color command if new > old by meaningful margin."""
    if np.isnan(val_old) or np.isnan(val_new):
        return ''
    if val_new - val_old > 0.005:
        return '\\cellcolor{green!10}'
    elif val_old - val_new > 0.005:
        return ''  # only highlight improvements
    return ''

def mean_val(r):
    m = r.get('mean')
    return m if m is not None else float('nan')

def n_seeds(r):
    return r.get('n', 0)

# ============================================================
# Row definitions: (label, combo_key, row_type)
# row_type controls formatting and annotation
# ============================================================
ROWS = [
    # ---- A: Single Filters ----
    ('\\midrule\\multicolumn{8}{l}{\\textbf{\\emph{A. Single Filter Baselines}}}\\\\', None, 'section'),
    ('sim (original)',                    'sim',     'old_single'),
    ('degree (original)',                 'degree',  'old_single'),
    ('ood (original)',                    'ood',     'old_single'),
    ('nsp (ours)',                        'nsp',     'new_single'),
    ('fc (ours)',                         'fc',      'new_single'),

    # ---- B: Replacement: sim -> nsp ----
    ('\\midrule\\multicolumn{8}{l}{\\textbf{\\emph{B. Controlled Replacement: sim $\\rightarrow$ nsp}}}\\\\', None, 'section'),
    ('\\quad sim+degree \\hfill(old)',    'sim+deg',   'old_base'),
    ('\\quad nsp+degree \\hfill(new)',    'deg+nsp',   'new_repl'),
    ('\\quad sim+ood \\hfill(old)',       'sim+ood',   'old_base'),
    ('\\quad nsp+ood \\hfill(new)',       'ood+nsp',   'new_repl'),

    # ---- C: Replacement: sim -> fc (baselines same as B) ----
    ('\\midrule\\multicolumn{8}{l}{\\textbf{\\emph{C. Controlled Replacement: sim $\\rightarrow$ fc}}}\\\\', None, 'section'),
    ('\\quad sim+degree \\hfill(old)',    'sim+deg',   'old_base2'),
    ('\\quad fc+degree \\hfill(new)',     'deg+fc',    'new_repl2'),
    ('\\quad sim+ood \\hfill(old)',       'sim+ood',   'old_base2'),
    ('\\quad fc+ood \\hfill(new)',        'ood+fc',    'new_repl2'),

    # ---- D: Three-Filter ----
    ('\\midrule\\multicolumn{8}{l}{\\textbf{\\emph{D. Three-Filter Comparison}}}\\\\', None, 'section'),
    ('sim+degree+ood \\hfill(all original)',  'sim+deg+ood',  'old_triple'),
    ('ood+nsp+fc \\hfill(best with new)',     'ood+nsp+fc',   'new_triple'),
]

# ============================================================
# Compute data
# ============================================================
rows_data = []
for label, combo, rtype in ROWS:
    if combo is None:
        rows_data.append((label, None, rtype, [None]*6, [None]*6))
        continue
    rd = nsp.get(combo, {})
    cells_str = [fmt(get_ptb(rd, p)) for p in PTBS]
    cells_val = [mean_val(get_ptb(rd, p)) for p in PTBS]
    cells_n   = [n_seeds(get_ptb(rd, p)) for p in PTBS]
    rows_data.append((label, cells_str, rtype, cells_val, cells_n))

# Global best per column (for bolding)
best_per_col = {}
for p_idx, p in enumerate(PTBS):
    best_val = -1
    for _, _, _, vals, _ in rows_data:
        if vals[p_idx] is not None and not np.isnan(vals[p_idx]):
            if vals[p_idx] > best_val:
                best_val = vals[p_idx]
    best_per_col[p_idx] = best_val

# ============================================================
# Build LaTeX
# ============================================================
L = []
L.append('% Auto-generated by reports/generate_latex_table.py')
L.append('% Narrative: sim is weak/unstable; nsp & fc are stable replacements.')
L.append('% p_plus=True, Peak BB, 5-shot Cora, 5 seeds, mean±std.')
L.append('\\begin{table}[t]')
L.append('\\centering')
L.append('\\caption{')
L.append('  \\textbf{Systematic filter replacement under Metattack.}')
L.append('  We identify \\texttt{sim\\_pt} as the weakest defense tip in GPromptShield')
L.append('  (lowest clean accuracy, unstable with missing seeds), and propose \\texttt{nsp\\_pt}')
L.append('  and \\texttt{fc\\_pt} as stable replacements. Controlled experiments (Sections~B--C)')
L.append('  show that replacing \\texttt{sim\\_pt} with \\texttt{nsp\\_pt} or \\texttt{fc\\_pt}')
L.append('  consistently improves accuracy across all perturbation levels.')
L.append('  All results use RobustPrompt-T-NSP on Cora (GraphCL-pretrained GCN, 256-dim),')
L.append('  5-shot per class, mean$\\pm$std over 5 seeds.')
L.append('  $^{\\dagger}$Fewer than 5 valid seeds (unstable convergence).}')

L.append('\\label{tab:filter_replacement}')
L.append('\\small')
L.append('\\setlength{\\tabcolsep}{4pt}')
L.append('\\begin{tabular}{@{}lcccccc@{}}')
L.append('\\toprule')
L.append(' & \\multicolumn{6}{c}{\\textbf{Metattack Perturbation Rate (ptb)}}\\\\')
ptb_hdr = ' & '.join(f'{p:.2f}' for p in PTBS)
L.append(f'\\textbf{{Filter Combination}} & {ptb_hdr}\\\\')
L.append('\\midrule')

# Emit rows
for i, (label, cells, rtype, vals, ns) in enumerate(rows_data):
    if rtype == 'section':
        L.append(f'  {label}')
        continue

    # Find the paired "old baseline" if this is a replacement row
    old_vals = None
    if rtype in ('new_repl', 'new_repl2'):
        # Look backward for the nearest old_base or old_base2 row
        target_base = 'old_base2' if rtype == 'new_repl2' else 'old_base'
        for j in range(i-1, -1, -1):
            if rows_data[j][2] == target_base:
                old_vals = rows_data[j][3]  # vals of the old baseline
                break

    # Build the row
    row_cells = [label]
    for p_idx in range(6):
        c = cells[p_idx]
        v = vals[p_idx]

        # Bold best in column
        if v is not None and not np.isnan(v) and abs(v - best_per_col[p_idx]) < 0.0005:
            c = f'\\mathbf{{{c}}}'

        # Highlight improvement over old baseline
        if old_vals is not None and v is not None and not np.isnan(v):
            ov = old_vals[p_idx]
            if ov is not None and not np.isnan(ov) and v - ov > 0.005:
                c = '\\cellcolor{green!15}{' + c + '}'

        row_cells.append(c)

    L.append('  ' + ' & '.join(row_cells) + ' \\\\')

L.append('\\bottomrule')
L.append('\\end{tabular}')
L.append('\\end{table}')

result = '\n'.join(L)
print(result)

with open('advanced_report/filter_comparison_table.tex', 'w', encoding='utf-8') as f:
    f.write(result)
print('\n% --- Saved to advanced_report/filter_comparison_table.tex ---')
